"""empty message

Revision ID: 047d246b25c0
Revises: 4ebcdba7067c
Create Date: 2023-05-11 22:49:21.175378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047d246b25c0'
down_revision = '4ebcdba7067c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', sa.String(length=8), nullable=False))
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
        batch_op.drop_column('contrasena')

    # ### end Alembic commands ###
