"""empty message

Revision ID: 119039c751c6
Revises: 22d57ac137c1
Create Date: 2023-05-12 20:59:31.474765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119039c751c6'
down_revision = '22d57ac137c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['correo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
