"""empty message

Revision ID: 22d57ac137c1
Revises: b3298d6e42c7
Create Date: 2023-05-12 19:13:17.273621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d57ac137c1'
down_revision = 'b3298d6e42c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('contrasena',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('contrasena',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
