"""empty message

Revision ID: 4ebcdba7067c
Revises: 40ba10153d17
Create Date: 2023-05-11 22:38:12.573416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebcdba7067c'
down_revision = '40ba10153d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', sa.String(length=8), nullable=False))
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
        batch_op.alter_column('telefono',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('contrasena')

    # ### end Alembic commands ###
