"""empty message

Revision ID: 895ba5e77571
Revises: 859fcfbd00c5
Create Date: 2023-05-11 20:00:17.550506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895ba5e77571'
down_revision = '859fcfbd00c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cobertura', sa.String(length=1000), nullable=True))
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('detalle',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.drop_column('region')
        batch_op.drop_column('cobertura_servicio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cobertura_servicio', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.alter_column('detalle',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('cobertura')

    # ### end Alembic commands ###
