"""empty message

Revision ID: b3298d6e42c7
Revises: 90341f1441d7
Create Date: 2023-05-12 18:43:50.370986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3298d6e42c7'
down_revision = '90341f1441d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', sa.String(length=8), nullable=False))
        batch_op.alter_column('telefono',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('contrasena')

    # ### end Alembic commands ###
