"""empty message

Revision ID: f28df4c26975
Revises: 047d246b25c0
Create Date: 2023-05-11 23:19:27.425872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28df4c26975'
down_revision = '047d246b25c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.String(length=8), nullable=False))
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('contrasena')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
        batch_op.alter_column('telefono',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###
